# Generated by Django 4.1.2 on 2022-10-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profilefeeditem'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profilefeeditem',
            table='ProfileFeedItem',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
